import turtle
import winsound
play = winsound.PlaySound("turkish.wav",winsound.SND_ASYNC)

tr = turtle.Turtle()
wn = turtle.Screen()
wn.setup(width=720,height=420)
wn.title("Turkish Flag")
wn.bgcolor("red")
tr.speed(1)
tr.shape("circle")
tr.color("red")
tr.up()
tr.goto(-200,-50)
tr.down()
tr.fillcolor("white")
tr.begin_fill()
tr.circle(150)
tr.end_fill()
tr.up()
tr.goto(-145,-25)
tr.down()
tr.fillcolor("red")
tr.begin_fill()
tr.circle(130)
tr.end_fill()
tr.up()
tr.goto(2,50)
tr.down()
tr.color("white")
tr.fillcolor("white")
tr.begin_fill()
tr.left(36)
tr.forward(100)
for i in range(4):
    tr.left(144)
    tr.forward(100)
tr.end_fill()
tr.up()
tr.hideturtle()
tr.goto(-250,-150)
tr.write("Ne Mutlu Türküm Diyene !!!" , font=("Verdana",17,"bold"))
turtle.mainloop()